// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqVzv3fKV0CuENkHkut3FkU3mjKhWQ_Fw',
    appId: '1:1086183871450:web:1405d0d61f8be80e3c26e3',
    messagingSenderId: '1086183871450',
    projectId: 'learnfirease',
    authDomain: 'learnfirease.firebaseapp.com',
    storageBucket: 'learnfirease.appspot.com',
    measurementId: 'G-X82V1GPRTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0nfEFj0nUlSailQHhJDwzL0KhnDKliFQ',
    appId: '1:1086183871450:android:e55e3eb3667c73d53c26e3',
    messagingSenderId: '1086183871450',
    projectId: 'learnfirease',
    storageBucket: 'learnfirease.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCudt_Gb992ZNK8tjf7-7I4eQNtuojOF7w',
    appId: '1:1086183871450:ios:e104e00d56a385ff3c26e3',
    messagingSenderId: '1086183871450',
    projectId: 'learnfirease',
    storageBucket: 'learnfirease.appspot.com',
    iosBundleId: 'com.example.learnFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCudt_Gb992ZNK8tjf7-7I4eQNtuojOF7w',
    appId: '1:1086183871450:ios:e104e00d56a385ff3c26e3',
    messagingSenderId: '1086183871450',
    projectId: 'learnfirease',
    storageBucket: 'learnfirease.appspot.com',
    iosBundleId: 'com.example.learnFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqVzv3fKV0CuENkHkut3FkU3mjKhWQ_Fw',
    appId: '1:1086183871450:web:ef99d62a06bf140e3c26e3',
    messagingSenderId: '1086183871450',
    projectId: 'learnfirease',
    authDomain: 'learnfirease.firebaseapp.com',
    storageBucket: 'learnfirease.appspot.com',
    measurementId: 'G-BYKX99JJW2',
  );
}
